import { StructureType, StructureDef } from '../types/voidHorde';

export const STRUCTURE_DEFS: Record<StructureType, StructureDef> = {
  auto_turret: {
    type: 'auto_turret',
    name: 'Auto Turret',
    description: 'Fast single-target automated turret. Excellent against swarmers and light units.',
    cost: 100,
    maxHp: 250,
    range: 280,
    damage: 28,
    fireRate: 4, // 4 shots per sec
    color: '#38bdf8',
  },
  heavy_cannon: {
    type: 'heavy_cannon',
    name: 'Heavy Cannon',
    description: 'Slow firing cannon with high splash damage. Great against armored groups.',
    cost: 180,
    maxHp: 400,
    range: 350,
    damage: 160,
    fireRate: 1.2,
    color: '#f97316',
  },
  laser_turret: {
    type: 'laser_turret',
    name: 'Laser Turret',
    description: 'Continuous thermal beam with increasing focus damage against single targets.',
    cost: 250,
    maxHp: 300,
    range: 320,
    damage: 45,
    fireRate: 10,
    color: '#ec4899',
  },
  slow_field: {
    type: 'slow_field',
    name: 'Cryo Shockwave Pusher',
    description: 'Triggers a heavy chilling frost slam that deals massive frost damage and violently shoves enemies away.',
    cost: 140,
    maxHp: 320,
    range: 240,
    damage: 60,
    fireRate: 0.5,
    color: '#06b6d4',
  },
  shield_generator: {
    type: 'shield_generator',
    name: 'Shield Generator',
    description: 'Projects a defensive energy dome that absorbs damage for nearby structures & players.',
    cost: 220,
    maxHp: 600,
    range: 250,
    damage: 0,
    fireRate: 0,
    color: '#8b5cf6',
  },
  repair_station: {
    type: 'repair_station',
    name: 'Repair Workshop',
    description: 'Automatically sends nanite pulses to repair damaged structures in its radius.',
    cost: 160,
    maxHp: 350,
    range: 260,
    damage: 0,
    fireRate: 1.5,
    color: '#10b981',
  },
  barricade: {
    type: 'barricade',
    name: 'Reinforced Wall',
    description: 'Durable physical barrier that stalls enemy progression along choke points.',
    cost: 80,
    maxHp: 800,
    range: 0,
    damage: 0,
    fireRate: 0,
    color: '#64748b',
  },
};
