import { WeaponType, WeaponStats } from '../types/voidHorde';

export const WEAPON_DEFS: Record<WeaponType, WeaponStats> = {
  plasma: {
    id: 'plasma',
    name: 'Plasma Blaster',
    description: 'Rapid-fire energy blaster with high accuracy and reliable single-target DPS.',
    damage: 35,
    fireRate: 8,
    projectileSpeed: 700,
    spread: 0.08,
    pellets: 1,
    color: '#38bdf8',
    cost: 0,
  },
  scatter: {
    id: 'scatter',
    name: 'Scatter Shotgun',
    description: 'Fires 6 energy pellets in a wide spread for close-range crowd control.',
    damage: 24,
    fireRate: 3.5,
    projectileSpeed: 580,
    spread: 0.35,
    pellets: 6,
    color: '#fbbf24',
    cost: 150,
  },
  assault: {
    id: 'assault',
    name: 'Pulse Rifle',
    description: 'Full-auto tactical assault rifle with balanced rate of fire and medium range.',
    damage: 42,
    fireRate: 9,
    projectileSpeed: 800,
    spread: 0.05,
    pellets: 1,
    color: '#34d399',
    cost: 200,
  },
  rocket: {
    id: 'rocket',
    name: 'Void Launcher',
    description: 'Launches heavy explosive rockets that detonate on impact.',
    damage: 240,
    fireRate: 1.2,
    projectileSpeed: 500,
    spread: 0.02,
    pellets: 1,
    color: '#f87171',
    cost: 350,
  },
  beam: {
    id: 'beam',
    name: 'Thermal Laser',
    description: 'Continuous high-frequency energy stream that burns through targets.',
    damage: 22,
    fireRate: 18,
    projectileSpeed: 1000,
    spread: 0.03,
    pellets: 1,
    color: '#f43f5e',
    cost: 400,
  },
  railgun: {
    id: 'railgun',
    name: 'Void Railgun',
    description: 'Fires heavy piercing antimatter beams that penetrate multiple enemies.',
    damage: 220,
    fireRate: 1.5,
    projectileSpeed: 1200,
    spread: 0.005,
    pellets: 1,
    color: '#c084fc',
    cost: 500,
  },
};
